server:
 servlet:
  contextPath: /token-proxy
spring:
 application:
  name: token-proxy
info:
 app:
  name: ms-token-proxy
  description: Modulo que contiene los servicios del token proxy
  version: 1.0.0
management:
 endpoints:
  web:
   exposure:
    include: info, *
default:
 locale: America/Mexico_City
oauth:
 server:
  token:
   url: https://ms-oauth2-server.herokuapp.com/auth-server/oauth
  security:
   header: Authorization
   secret: Basic YWRtaW5nZW50ZXJhOnBhc3N3b3Jk